### ISSUE TITLE
Change to GraalVM JS breaks state variables with multiple "." in name

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/yaup#18]
see: https://github.com/Hyperfoil/qDup/issues/45

evaluating a state name with multiple dots "." throws the following exception;

```
SyntaxError: Unnamed:1:19 Expected ; but found .1
getting-started.jvm.1.pid
                   ^

	at org.graalvm.polyglot.Context.eval(Context.java:370)
	at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:132)
	at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:53)
	at io.hyperfoil.tools.qdup.cmd.Cmd.getStateValue(Cmd.java:507)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:529)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:518)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:511)
	at io.hyperfoil.tools.qdup.cmd.impl.Sh.run(Sh.java:41)
	at io.hyperfoil.tools.qdup.cmd.Cmd.doRun(Cmd.java:891)
	at io.hyperfoil.tools.qdup.cmd.ScriptContext.run(ScriptContext.java:431)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by willr3** [comment]
The issue was the `-` in `getting-started` made the pattern look like a javascript arithmetic operation. the pattern will not only try javascript operations if the name is not in the variable map.
87e3eab
